### PR TITLE
React v14

### PR DESCRIPTION
**Pull request by jmsv23**
This pull request includes fixes to remove warnings on React.js v 14, also add a behavior to close the dropdown when the user click outside the component.

### CODE REVIEW

**Comment by alsoscotland** [comment]
@jmsv23  Thanks for making this pull.  Looks great at first glance.  I am going to pull it and verify a few things and then I'll work on getting things merged for the React 14 upgrade

**Comment by alsoscotland** [comment]
@jmsv23 pulled your code in tonight.  Making progress but still have some work upgrading the jest specs in my branch for React 14. I have cherry-picked the React 14 updates from your commit 7a330a5

At the moment I am leaning towards not adding the event listeners on document for clicking/closing outside the control.  While it makes sense for some potential use-cases, it may not be general enough for all use cases.

**Comment by jmsv23** [comment]
Great, i am glad to help, this saved me alot of time in one of my current projects thanks for the componente

**Comment by alsoscotland** [comment]
@jmsv23  
I have published https://github.com/alsoscotland/react-super-select/tree/v0.2.0 in order to be React 14 compatible.  Thank you for your help.  I opted not to include the click event wiring on document for the time being

**Pull request closed without merging**
